-- noinspection SqlNoDataSourceInspectionForFile

# --- !Ups

create table "photos" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "user" varchar not null,
);

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "username" varchar not null,
  "email" varchar not null,
);

INSERT INTO "users" ("id", "username", "email")
VALUES (1, 'jm', 'j@j.com');

# --- !Downs

drop table "photos" if exists;
drop table "users" if exists;
