-- noinspection SqlNoDataSourceInspectionForFile

# --- !Ups

create table "photos" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "user" varchar not null,
);

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "username" varchar not null,
  "email" varchar not null,
);

create table "albums" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "description" varchar not null,
);

INSERT INTO "users" ("username", "email")
VALUES ('jm', 'j@j.com');

INSERT INTO "albums" ("title", "description")
VALUES ('Brenda + Juli', 'The good times')

# --- !Downs

drop table "photos" if exists;
drop table "users" if exists;
